
DROP TABLE TBL_BOARD_MASTER;

CREATE TABLE TBL_BOARD_MASTER(
    GCODE	VARCHAR(50) NOT NULL,
    DEPTH	VARCHAR(50) NOT NULL,
    GTITLE	VARCHAR(50) NOT NULL,
    ETC1	VARCHAR(50) ,
    ETC2	VARCHAR(50) ,
    ETC3	VARCHAR(50) ,
    WRITER  VARCHAR2(50) NOT NULL,
    FIRSTREGISTER VARCHAR2(50) NOT NULL,
    REGDATE DATE DEFAULT SYSDATE,
    LASTREGISTER  VARCHAR2(50) NOT NULL,
    UPDATEDATE DATE DEFAULT SYSDATE
);





create sequence seq_board;

COMMIT;


CREATE TABLE TBL_BOARD(
    BNO     NUMBER(10,0) NOT NULL,
    GCODE	VARCHAR(50) NOT NULL,
    TITLE   VARCHAR2(200) NOT  NULL,
    CONTENT VARCHAR2(2000) NOT NULL,
    WRITER  VARCHAR2(50) NOT NULL,
    FIRSTREGISTER VARCHAR2(50) NOT NULL,
    REGDATE DATE DEFAULT SYSDATE,
    LASTREGISTER  VARCHAR2(50) NOT NULL,
    UPDATEDATE DATE DEFAULT SYSDATE
);


COMMIT;

/* MASTER INSERT  */

INSERT INTO MULTIBOARD_EX.TBL_BOARD_MASTER
(GCODE, "DEPTH", GTITLE, ETC1, ETC2, ETC3, WRITER, FIRSTREGISTER, REGDATE, LASTREGISTER, UPDATEDATE)
VALUES('COMU', '1', '커뮤니티', '', '', '', '푸초취리', 'doawishfor', SYSDATE, 'doawishfor', SYSDATE
);


/* MASTER SELECT */
SELECT GCODE, "DEPTH", GTITLE, ETC1, ETC2, ETC3, WRITER, FIRSTREGISTER, REGDATE, LASTREGISTER, UPDATEDATE
FROM MULTIBOARD_EX.TBL_BOARD_MASTER;


/* MASTER UPDATE */
UPDATE MULTIBOARD_EX.TBL_BOARD_MASTER
SET GCODE='COMMUNITY', "DEPTH"='1', GTITLE='동네커뮤니티', ETC1='', ETC2='', ETC3='', WRITER='푸초취리', LASTREGISTER='doawishfor', UPDATEDATE=SYSDATE
;

/* MASTER DELETE  */
DELETE FROM MULTIBOARD_EX.TBL_BOARD_MASTER
WHERE GCODE='COMMUNITY'; 

COMMIT;

/* TBL_BOARD INSERT */
INSERT INTO MULTIBOARD_EX.TBL_BOARD
(BNO, GCODE, TITLE, CONTENT, WRITER, FIRSTREGISTER, REGDATE, LASTREGISTER, UPDATEDATE)
VALUES(seq_board.nextval, 'COMMUNITY', 'TESTTITLE', 'TESTCONTENT', '푸초취리', 'doawishfor', SYSDATE, 'doawishfor', SYSDATE
);

SELECT seq_board;


/* TBL_BOARD SELECT */
SELECT BNO, GCODE, TITLE, CONTENT, WRITER, FIRSTREGISTER, REGDATE, LASTREGISTER, UPDATEDATE
FROM MULTIBOARD_EX.TBL_BOARD;


/* TBL_BOARD UPDATE */
UPDATE MULTIBOARD_EX.TBL_BOARD
SET TITLE='TITLEUPDATE', CONTENT='CONTENTUPDATE', LASTREGISTER='doawishfor', UPDATEDATE=SYSDATE
;

/* TBL_BOARD DELETE */
DELETE FROM MULTIBOARD_EX.TBL_BOARD
WHERE BNO=1 AND GCODE='COMMUNITY'; 
;

